- name: MariaDB installation
  hosts: mariadbs
  become: yes
  tasks:
    - name: Install MariaDB server
      apt: 
        name: mariadb-server
        state: latest
    - name: start MariaDB service
      systemd:
        name: mariadb
        state: started
    - name: verify installation
      ansible.builtin.command: mysql --version
      register: mysql_version
    - debug: var=mysql_version.stdout_lines
